### ISSUE TITLE
Unknown function: path

### ISSUE THREAD

**Issue by henrikrudstrom** [sanity-io/groq-js#7]
Got another one:
running this query
```
const query = groq`*[
        _type == 'staticPage' &&
        !(_id in path("drafts.**")) &&
        slug.current == $slug &&
        publication._ref == $publicationId
    ][0]`
```
produces this error:
```
Unknown function: path

at FuncCall (node_modules/groq-js/src/evaluator/index.js:78:22)
      at execute (node_modules/groq-js/src/evaluator/index.js:46:10)
      at inop (node_modules/groq-js/src/evaluator/operators.js:75:23)
      at Parenthesis (node_modules/groq-js/src/evaluator/index.js:220:21)
      at Not (node_modules/groq-js/src/evaluator/index.js:382:17)
      at And (node_modules/groq-js/src/evaluator/index.js:365:22)
      at And (node_modules/groq-js/src/evaluator/index.js:364:21)
      at And (node_modules/groq-js/src/evaluator/index.js:364:21)
      at StreamValue._generator (node_modules/groq-js/src/evaluator/index.js:98:27)
      at fetch (node_modules/groq-js/src/evaluator/value.js:131:22)
```

is this just as quick a fix?  ;)

**Comment by judofyr** [comment]
That one is unfortunately not such a quick fix. To do it properly I need to add `Path` to [the spec](https://github.com/sanity-io/GROQ). I have a tracking issue for it here: https://github.com/sanity-io/GROQ/issues/9.

I'll see if I can get it done by next week (Sep 18th).
